pretrained_model_name_or_path: stabilityai/stable-video-diffusion-img2vid-xt
revision: null
validation_prompt: null
num_frames: 25
width: 256
height: 128
num_validation_images: 1
validation_steps: 500
seed: 23
per_gpu_batch_size: 1
num_train_epochs: 20
max_train_steps: null
gradient_accumulation_steps: 1
gradient_checkpointing: false
learning_rate: 3.0e-06
scale_lr: false
lr_scheduler: constant
lr_warmup_steps: 500
conditioning_dropout_prob: 0.1
use_8bit_adam: false
allow_tf32: false
use_ema: false
non_ema_revision: null
num_workers: 8
adam_beta1: 0.9
adam_beta2: 0.999
adam_weight_decay: 0.01
adam_epsilon: 1.0e-08
max_grad_norm: 1.0
push_to_hub: false
hub_token: null
hub_model_id: null
logging_dir: logs
mixed_precision: fp16
report_to: tensorboard
local_rank: -1
checkpointing_steps: 500
checkpoints_total_limit: 2
resume_from_checkpoint: null
enable_xformers_memory_efficient_attention: false
pretrain_unet: null
rank: 128
